### PR TITLE
Updating NWSTokenView to support Swift 4.2

### PR DESCRIPTION
**Pull request by mike011**
- Updated pod version from 2.0.3 to 2.0.4
- Updated Xcode from 8 to 10
- Most of the corrections where applying auto fixes.
- Also applied updates to Swift and Pod project.
- Did a pod install the Example folder to update the app to run 2.0.4
- Ran the app and it works just like it before.
- This PR addresses #22

### CODE REVIEW

**Comment by AdamLee321** [comment]
Can you complete the pull request,I would like to try and use this library thanks.

**Comment by JimmyJammed** [comment]
Looks good! I’ll update the pod shortly.
Thanks for contributing! 🍻

**Comment by JimmyJammed** [comment]
@mike011 @AdamLee321 The updates have been merged in. Please note I won't be able to update the actual pod as this one is tied to my old company/email that I dissolved a couple years ago. I submitted a request to claim it with my new accounts, so will update it once thats processed. 

In the meantime you can point your pod to latest using this line in your pod file:

`pod 'NWSTokenView', :git => 'https://github.com/Appmazo/NWSTokenView.git'`

Cheers! 🍻

**Comment by JimmyJammed** [comment]
@mike011 @AdamLee321 CocoaPod has been updated to `v2.0.4`. You can now use latest version with: `pod 'NWSTokenView'`

Cheers! 🍻

**Pull request merged**
